[package]
name = "rqoob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.hidapi]
version = "2.6.1"
default-features = false
features = ["linux-native", "windows-native"]
